//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPMnc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoaHoc
    {
        public int MaKhoaHoc { get; set; }
        public string TenKhoaHoc { get; set; }
        public Nullable<int> SoluongSV { get; set; }
        public Nullable<int> MaGV { get; set; }
        public Nullable<int> MaSV { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<int> SoTiet { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
