//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPMnc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.SinhViens = new HashSet<SinhVien>();
        }
    
        public int MaTaiKhoan { get; set; }
        public Nullable<int> MaGV { get; set; }
        public Nullable<int> MaSV { get; set; }
        public Nullable<int> MaPQ { get; set; }
        public string TenTaiKhoan { get; set; }
        public string Matkhau { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual PhanQuyen PhanQuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVien> SinhViens { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
